BEGIN;

DROP DATABASE IF EXISTS books, CASCADE;

CREATE TABLE books(
  id INT AUTO_INCREMENT,
  title VARCHAR(200) NOT NULL,
  author VARCHAR(200) NOT NULL,
  description TEXT,
  published_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
  PRIMARY KEY(id)
)

COMMIT;